Portfolio contact form
Booze33/My-Portfolio pull request #5
Opened 2023-02-21 21:32 UTC by Booze33

Created new pull-request for the branch

2023-02-21 22:01 UTC, vickymarz requested changes
Hi @Booze33, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## ❌ Invalid Code Review Request

You have submitted a project that does not have a descriptive pull request summary describing the changes implemented in the pull request. Kindly highlight the things you implemented in your pull request summary.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-21 22:43 UTC, souad988 requested changes
Hi @Booze33 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![212385281-4797c58a-d358-423a-aa7c-832c22203865](https://user-images.githubusercontent.com/59707859/220475329-6b2c0cd7-5599-412f-b4a0-7c02ced2ec0f.gif)


## Highlights
✔No linter errors
✔Very good and easy to understand commit messages 💪.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 22:43 UTC, souad988 commented on index.html
> +    <form method="" action="">
kindly fill the method and action attributes as requested in this project requirements.

2023-02-21 22:43 UTC, souad988 commented on index.html
> +        <button type="submit">Get in touch</button>
good job on implementing this part , Only one small issue to mention here your button has a different padding and font size , please make sure to replicate figma design as you can.
**your button:**

![button padding student temp1](https://user-images.githubusercontent.com/59707859/220474273-1cbdd2b4-c08a-4f90-8d3e-6d6a912e6eab.PNG)

**figma design:**

![button padding temp1](https://user-images.githubusercontent.com/59707859/220474278-2ada2e82-5daa-4f89-8301-d6c1e770f8eb.PNG)

2023-02-21 22:43 UTC, souad988 commented on style.css
> +  #email {
kindly add a padding left to all placeholder text in your inputs 😊
**your design:**

![placeholder padding left  student](https://user-images.githubusercontent.com/59707859/220474767-b33f299f-b9c5-4f20-b811-35b0c046b2ef.PNG)

**figma design:**

![placeholder padding left](https://user-images.githubusercontent.com/59707859/220474771-c2c81f16-3e70-4000-95f2-141a67e338e1.PNG)

2023-02-22 00:11 UTC, Kossi-stack approved these changes
## Status: Approved ✔️

**Hi @Booze33,**

You did a really great job! 💯 💯💯💯
Congratulations! 🎉 🎉 🎉 🎉 

![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/81444338/150871274-7d1b779c-88e6-420b-a530-b7b905eaa3ac.gif)

You may close this Pull Request and merge the changes
Keep being awesome dev's and good luck with your next milestone!

## To Highlight

✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ README file is descriptive.
✅ Commit messages are meaningful.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏 👏 👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2023-02-22 14:45 UTC, Booze33 commented
Passed the review.
-close pull request

2023-02-22 14:47 UTC, merged